export const REGISTER_BOX_OPEN = '/register/REGISTER_BOX_OPEN'
export const REGISTER_BOX_CLOSE = '/register/REGISTER_BOX_CLOSE'
export const REGISTER_START = '/register/REGISTER_START'
export const REGISTER_SUCCESSFUL = '/register/REGISTER_SUCCESSFUL'
export const REGISTER_FAIL = '/register/REGISTER_FAIL'
