name: Update News Database

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run update script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PWD: ${{ secrets.MYSQL_PWD }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: node ./update-script.js
        working-directory: ./server/service
