export const LOGIN_BOX_OPEN = '/login/LOGIN_BOX_OPEN'
export const LOGIN_BOX_CLOSE = '/login/LOGIN_BOX_CLOSE'
export const LOGIN_START = '/login/LOGIN_START'
export const LOGIN_SUCCESSFUL = '/login/LOGIN_SUCCESSFUL'
export const LOG_OUT_SUCCESS = '/login/LOG_OUT_SUCCESS'
export const LOGIN_FAIL = '/login/LOGIN_FAIL'
export const SET_USER = '/login/SET_USER'
