export const CHANGE_ISOPEN_STATE = '/header/CHANGE_ISOPEN_STATE'
export const CHANGE_ISOPEN_STATE_TO_OPEN = '/header/CHANGE_ISOPEN_STATE_TO_OPEN'
export const OPEN_TO_TOP_ICON = '/header/OPEN_TO_TOP_ICON'
export const CLOSE_TO_TOP_ICON = '/header/CLOSE_TO_TOP_ICON'
